server:
  port: 80

# ==========applicationName + druid-mysql8 driver===================
spring:
  application:
    name: cloud-consumer-order

  ###Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: 192.168.57.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      health-check-url: http://192.168.57.100:8500/management/health
      heartbeat:
        enabled: true
